### ISSUE TITLE
bokeh application error

### ISSUE THREAD

**Issue by itsmylife44** [gotzl/acctelemetry#2]
Hello , i'm trying to open the telemetry files , without success .. 

![image](https://user-images.githubusercontent.com/34112129/78949184-2b340280-7acb-11ea-9136-92f181841882.png)

log :

`$ bokeh serve --show acctelemetry.py
2020-04-10 01:30:52,038 Starting Bokeh server version 2.0.1 (running on Tornado 6.0.4)
2020-04-10 01:30:52,039 User authentication hooks NOT provided (default user enabled)
2020-04-10 01:30:52,041 Bokeh app running at: http://localhost:5006/acctelemetry
2020-04-10 01:30:52,041 Starting Bokeh server with process id: 16940
2020-04-10 01:30:53,164 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x000002AF3AAE6280>: cannot import name 'ldparser' from 'ldparser' (unknown location)
File "acctelemetry.py", line 13, in <module>:
from ldparser import ldparser Traceback (most recent call last):
  File "c:\users\xspam\appdata\local\programs\python\python38\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\Users\xSpaM\Desktop\acctelemetry-master\acctelemetry.py", line 13, in <module>
    from ldparser import ldparser
ImportError: cannot import name 'ldparser' from 'ldparser' (unknown location)

2020-04-10 01:30:53,417 WebSocket connection opened
2020-04-10 01:30:53,417 ServerConnection created
`

**Comment by gotzl** [comment]
Uh, windows... Never tried it there ;)
In any case, I believe the main issue here is that you didn't checkout the git submodules. In linux, I would do
```
git submodule update --init
```
in the acctelemetry-master folder.

**Comment by itsmylife44** [comment]
> Uh, windows... Never tried it there ;)
> In any case, I believe the main issue here is that you didn't checkout the git submodules. In linux, I would do
> 
> ```
> git submodule update --init
> ```
> 
> in the acctelemetry-master folder.

![image](https://user-images.githubusercontent.com/34112129/79927195-4a258380-843f-11ea-94c5-d836756e6f58.png)

**Comment by gotzl** [comment]
Hi,
no idea why this does not work for you. 
Could you checkout the latest version? I've updated the path to the submodule using https, maybe that works better for you? Also, I've realized that you use bokeh>=2, which I did not test (and does not work) so I've updated the requirements.txt to require bokeh<2.
Then, when you run the app, you need to supply a path, ie `bokeh serve --show ./`.
